#!/usr/bin/env python3
"""
Indian-dusk GitHub profile banner generator  ("mandala" theme).

What's accurate now
  * COMMITS   - all-time, since your account was created. Uses GitHub's GraphQL
                contributions API year-by-year (same numbers as your profile
                graph), with a per-repo REST fallback. Also yields commits/year.
  * LOC       - real non-blank lines of source from a checkout of every repo,
                skipping lockfiles, minified/generated files, vendored and
                build folders. No more "1 commit per repo" shallow-clone bug.
  * LANGUAGES - computed from those same lines, so the chart and the LOC card
                always agree (the old chart used API byte counts).

Optional: add a Personal Access Token (scopes: read:user, repo) as the repo
secret STATS_TOKEN to include private repos and private commits.
"""
import os
import re
import sys
import json
import math
import random
import shutil
import subprocess
import tempfile
import datetime
import urllib.request
from html import escape
from pathlib import Path

# ============================================================================
#  CONFIG
# ============================================================================
USERNAME = os.environ.get("GITHUB_USERNAME", "vikasranax")
THEMES = ["mandala"]
# Also write the banner under these legacy names so your README <img> keeps working
ALSO_WRITE_AS = ["saltflats"]

TOKEN = os.environ.get("STATS_TOKEN") or os.environ.get("GITHUB_TOKEN", "")
INCLUDE_FORKS = False
INCLUDE_PRIVATE = True        # only effective when STATS_TOKEN is your own PAT
TOP_LANGUAGES = 6
MAX_YEARS_SHOWN = 8
REQUEST_TIMEOUT = 30
OUT_DIR = Path("assets")
# ============================================================================

W, H = 1200, 640
SANS = "IBM Plex Sans, Segoe UI, Noto Sans, Noto Sans Devanagari, Arial, sans-serif"
MONO = "IBM Plex Mono, SFMono-Regular, Consolas, Menlo, monospace"
DISP = "Space Grotesk, Noto Sans Devanagari, Mukta, Segoe UI, sans-serif"

LANG_COLORS = {
    "TypeScript": "#3178c6", "JavaScript": "#f1e05a", "HTML": "#e34c26",
    "CSS": "#8a5cf5", "SCSS": "#c6538c", "Python": "#4b8bbe", "C++": "#f34b7d",
    "C": "#9aa0a6", "Java": "#b07219", "Dockerfile": "#4f7f96", "Shell": "#89e051",
    "Go": "#00add8", "Rust": "#dea584", "Ruby": "#cc342d", "PHP": "#8892bf",
    "Swift": "#ffac45", "Kotlin": "#a97bff", "C#": "#37a02c", "Vue": "#41b883",
    "Svelte": "#ff3e00", "Dart": "#00b4ab", "Lua": "#5b5bd6", "SQL": "#e38c00",
}

EXT_LANG = {
    ".py": "Python", ".pyi": "Python", ".js": "JavaScript", ".jsx": "JavaScript",
    ".mjs": "JavaScript", ".cjs": "JavaScript", ".ts": "TypeScript",
    ".tsx": "TypeScript", ".html": "HTML", ".htm": "HTML", ".css": "CSS",
    ".scss": "SCSS", ".sass": "SCSS", ".less": "CSS", ".c": "C", ".h": "C",
    ".cpp": "C++", ".cxx": "C++", ".cc": "C++", ".hpp": "C++", ".hh": "C++",
    ".cs": "C#", ".java": "Java", ".kt": "Kotlin", ".kts": "Kotlin",
    ".swift": "Swift", ".go": "Go", ".rs": "Rust", ".rb": "Ruby", ".php": "PHP",
    ".sh": "Shell", ".bash": "Shell", ".zsh": "Shell", ".lua": "Lua",
    ".sql": "SQL", ".vue": "Vue", ".svelte": "Svelte", ".dart": "Dart",
}
SKIP_DIRS = {
    "node_modules", "vendor", "dist", "build", "out", ".next", ".nuxt", "coverage",
    "__pycache__", ".venv", "venv", "site-packages", "third_party", "third-party",
    "bower_components", "target", "pods", "deriveddata", ".gradle", ".dart_tool",
    ".git", ".idea", ".vscode",
}
SKIP_FILENAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock",
    "pipfile.lock", "cargo.lock", "composer.lock", "gemfile.lock", "go.sum",
}
GENERATED_MARKERS = (b"@generated", b"auto-generated", b"autogenerated",
                     b"automatically generated", b"do not edit")


# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
def ordinal_suffix(day):
    if 11 <= day <= 13:
        return "th"
    return {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")


def format_ist_now():
    utc = datetime.datetime.now(datetime.timezone.utc)
    ist = utc + datetime.timedelta(hours=5, minutes=30)
    return ist.strftime(f"%d{ordinal_suffix(ist.day)} %B %Y · %I:%M %p IST")


def mask(text):
    text = str(text)
    return text.replace(TOKEN, "***") if TOKEN else text


def _request(url, payload=None):
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", f"{USERNAME}-banner-generator")
    if data:
        req.add_header("Content-Type", "application/json")
    if TOKEN:
        req.add_header("Authorization", f"Bearer {TOKEN}")
    try:
        with urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT) as resp:
            return json.loads(resp.read().decode() or "null"), resp.headers
    except Exception as e:
        print(f"API error for {url}: {mask(e)}", file=sys.stderr)
        return None, {}


def api_call(url):
    return _request(url)[0]


def fmt(n):
    return f"{int(n):,}"


# ----------------------------------------------------------------------------
# Repos
# ----------------------------------------------------------------------------
def fetch_repos():
    me = api_call("https://api.github.com/user") if TOKEN else None
    is_owner = isinstance(me, dict) and str(me.get("login", "")).lower() == USERNAME.lower()
    if is_owner:
        base = "https://api.github.com/user/repos?affiliation=owner&visibility=all"
    else:
        base = f"https://api.github.com/users/{USERNAME}/repos?type=owner"
    repos, page = [], 1
    while page <= 10:
        data = api_call(f"{base}&per_page=100&page={page}&sort=updated")
        if not isinstance(data, list) or not data:
            break
        repos.extend(data)
        if len(data) < 100:
            break
        page += 1
    out = []
    for r in repos:
        if r.get("fork") and not INCLUDE_FORKS:
            continue
        if r.get("private") and not INCLUDE_PRIVATE:
            continue
        out.append(r)
    return out


# ----------------------------------------------------------------------------
# Lines of code (real checkout, real lines)
# ----------------------------------------------------------------------------
def detect_language(path_bytes):
    low = path_bytes.decode("utf-8", "ignore").lower()
    parts = low.split("/")
    name = parts[-1]
    if any(p in SKIP_DIRS for p in parts[:-1]):
        return None
    if name in SKIP_FILENAMES or name.endswith((".min.js", ".min.css", ".min.mjs", ".d.ts", ".map")):
        return None
    if name == "dockerfile" or name.startswith("dockerfile."):
        return "Dockerfile"
    return EXT_LANG.get(os.path.splitext(name)[1])


def count_lines(path):
    """Non-blank lines; 0 for binary, huge, minified or generated files."""
    try:
        if path.stat().st_size > 1_000_000:
            return 0
        data = path.read_bytes()
    except OSError:
        return 0
    if b"\0" in data[:8192]:
        return 0
    head = data[:2048].lower()
    if any(m in head for m in GENERATED_MARKERS):
        return 0
    lines = data.splitlines()
    if not lines or len(data) / len(lines) > 300:       # minified
        return 0
    return sum(1 for ln in lines if ln.strip())


def measure_repo(full_name, dest):
    """Clone (shallow is fine for LOC) and return {language: lines}."""
    auth = f"x-access-token:{TOKEN}@" if TOKEN else ""
    url = f"https://{auth}github.com/{full_name}.git"
    env = dict(os.environ, GIT_TERMINAL_PROMPT="0")
    try:
        subprocess.run(["git", "clone", "--depth", "1", "--quiet", url, str(dest)],
                       check=True, timeout=300, env=env,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        listed = subprocess.run(["git", "-C", str(dest), "ls-files", "-z"],
                                capture_output=True, check=True).stdout
    except Exception as e:
        print(f"clone/measure failed for {full_name}: {mask(e)}", file=sys.stderr)
        return {}
    by_lang = {}
    for f in listed.split(b"\0"):
        if not f:
            continue
        lang = detect_language(f)
        if not lang:
            continue
        n = count_lines(dest / f.decode("utf-8", "ignore"))
        if n:
            by_lang[lang] = by_lang.get(lang, 0) + n
    return by_lang


# ----------------------------------------------------------------------------
# Commits (all-time, since account creation)
# ----------------------------------------------------------------------------
def commits_by_year(created):
    """GraphQL, one aliased window per year. Returns {year: commits} or None."""
    if not TOKEN or not created:
        return None
    now = datetime.datetime.now(datetime.timezone.utc)
    iso = lambda d: d.strftime("%Y-%m-%dT%H:%M:%SZ")
    years = list(range(created.year, now.year + 1))
    parts = []
    for y in years:
        start = max(created, datetime.datetime(y, 1, 1, tzinfo=datetime.timezone.utc))
        end = min(datetime.datetime(y, 12, 31, 23, 59, 59, tzinfo=datetime.timezone.utc), now)
        parts.append(f'y{y}: contributionsCollection(from: "{iso(start)}", to: "{iso(end)}") '
                     f'{{ totalCommitContributions }}')
    query = "query($login:String!){ user(login:$login){ " + " ".join(parts) + " } }"
    data, _ = _request("https://api.github.com/graphql",
                       {"query": query, "variables": {"login": USERNAME}})
    try:
        u = data["data"]["user"]
        return {y: int(u[f"y{y}"]["totalCommitContributions"]) for y in years}
    except Exception:
        print(f"GraphQL commit query failed: {mask(json.dumps(data)[:300])}", file=sys.stderr)
        return None


def rest_commit_count(full_name):
    """Fallback: commits authored by USERNAME in one repo (default branch)."""
    url = f"https://api.github.com/repos/{full_name}/commits?author={USERNAME}&per_page=1"
    data, headers = _request(url)
    if not isinstance(data, list):
        return 0
    m = re.search(r'[?&]page=(\d+)>; rel="last"', headers.get("Link", "") if headers else "")
    return int(m.group(1)) if m else len(data)


# ----------------------------------------------------------------------------
# Collect everything
# ----------------------------------------------------------------------------
def fetch_stats():
    user = api_call(f"https://api.github.com/users/{USERNAME}") or {}
    created = None
    try:
        created = datetime.datetime.strptime(user["created_at"], "%Y-%m-%dT%H:%M:%SZ") \
            .replace(tzinfo=datetime.timezone.utc)
    except Exception:
        pass

    repos = fetch_repos()
    lang_lines, stars = {}, 0
    tmp = Path(tempfile.mkdtemp(prefix="banner-repos-"))
    print(f"{'repo':32} {'lines':>9}")
    try:
        for r in repos:
            stars += r.get("stargazers_count", 0)
            full = r.get("full_name", f"{USERNAME}/{r['name']}")
            by_lang = measure_repo(full, tmp / r["name"])
            for lang, n in by_lang.items():
                lang_lines[lang] = lang_lines.get(lang, 0) + n
            print(f"{r['name'][:32]:32} {sum(by_lang.values()):>9,}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    per_year = commits_by_year(created)
    if per_year is not None:
        total_commits = sum(per_year.values())
        source = "graphql"
    else:
        total_commits = sum(rest_commit_count(r.get("full_name", f"{USERNAME}/{r['name']}")) for r in repos)
        source = "rest-fallback"
    print(f"commits: {total_commits:,} ({source})")

    total_loc = sum(lang_lines.values())
    top = sorted(lang_lines.items(), key=lambda x: x[1], reverse=True)[:TOP_LANGUAGES]
    denom = total_loc or 1
    languages = [(lang, n, n / denom * 100) for lang, n in top]

    years_active = None
    if created:
        years_active = max(1, round((datetime.datetime.now(datetime.timezone.utc) - created).days / 365.25))

    return {
        "name": user.get("name") or USERNAME,
        "repos": len(repos), "stars": stars,
        "commits": total_commits, "loc": total_loc,
        "languages": languages,
        "per_year": per_year or {},
        "since": created.strftime("%b %Y") if created else "",
        "years_active": years_active,
    }


# ----------------------------------------------------------------------------
# Artwork: Indian dusk - rising sun mandala, shikhara temple, pagoda, stupa,
# Himalayan ridges, diyas floating on a lotus pond.  Pure SVG, tiny CSS motion.
# ----------------------------------------------------------------------------
CSS = """
.tw{animation:tw 4s ease-in-out infinite}
@keyframes tw{0%,100%{opacity:.2}50%{opacity:1}}
.fl{animation:fl 2.4s ease-in-out infinite;transform-box:fill-box;transform-origin:50% 100%}
@keyframes fl{0%,100%{transform:scale(1,1)}50%{transform:scale(.86,1.14)}}
.dr{animation:dr 50s ease-in-out infinite alternate}
@keyframes dr{from{transform:translateX(-35px)}to{transform:translateX(35px)}}
.rot{animation:rot 260s linear infinite;transform-origin:605px 290px}
@keyframes rot{to{transform:rotate(360deg)}}
@media (prefers-reduced-motion:reduce){*{animation:none!important}}
"""

GOLD = "#f2c47a"


def _puff(gid, color, op):
    return (f"<radialGradient id='{gid}' cx='0.5' cy='0.5' r='0.5'>"
            f"<stop offset='0' stop-color='{color}' stop-opacity='{op}'/>"
            f"<stop offset='0.55' stop-color='{color}' stop-opacity='{op*0.5:.2f}'/>"
            f"<stop offset='1' stop-color='{color}' stop-opacity='0'/></radialGradient>")


def _ridge(seed, base, amp, step=22):
    rnd = random.Random(seed)
    ph = [rnd.uniform(0, 6.28) for _ in range(3)]
    pts, x = [], -20
    while x <= 1220:
        n = (math.sin(x / 170 + ph[0]) * .5 + math.sin(x / 71 + ph[1]) * .3
             + math.sin(x / 33 + ph[2]) * .15 + rnd.uniform(-.25, .25) * .3)
        valley = .35 + .65 * min(1, abs(x - 605) / 260)      # keep the sun visible
        pts.append((x, base - amp * valley * (n * .5 + .5)))
        x += step
    return ("M -20 470 L " + " L ".join(f"{px:.0f} {py:.0f}" for px, py in pts) + " L 1220 470 Z")


def _temple(cx, by, s, fill, glow):
    side = ("<g transform='translate({x},-12) scale(.5)'>"
            "<path d='M -26 0 L -26 -26 Q -25 -72 -10 -100 Q -4 -110 0 -116 Q 4 -110 10 -100 "
            "Q 25 -72 26 -26 L 26 0 Z'/><ellipse cx='0' cy='-108' rx='10' ry='3.6'/>"
            "<rect x='-1' y='-134' width='2' height='24'/></g>")
    return (f"<g transform='translate({cx},{by}) scale({s})' fill='{fill}'>"
            "<rect x='-72' y='-5' width='144' height='5'/><rect x='-62' y='-11' width='124' height='6'/>"
            "<path d='M -26 -11 L -26 -38 Q -25 -84 -10 -112 Q -4 -122 0 -128 Q 4 -122 10 -112 "
            "Q 25 -84 26 -38 L 26 -11 Z'/>"
            "<ellipse cx='0' cy='-120' rx='10' ry='3.6'/><circle cx='0' cy='-132' r='3.2'/>"
            "<rect x='-1' y='-152' width='2' height='24'/><path d='M 1 -152 L 15 -148 L 1 -144 Z'/>"
            + side.format(x=-46) + side.format(x=46)
            + f"<path d='M -6 -11 L -6 -24 Q 0 -34 6 -24 L 6 -11 Z' fill='{glow}'/></g>")


def _pagoda(cx, by, s, fill):
    parts, y = [], 0.0
    for i in range(5):
        w = 30 - i * 4.5
        hb = 14 - i * .8
        parts.append(f"<rect x='{-w*.7:.1f}' y='{y-hb:.1f}' width='{w*1.4:.1f}' height='{hb:.1f}'/>")
        y -= hb
        parts.append(
            f"<path d='M {-(w+10):.1f} {y-5:.1f} Q {-w*.9:.1f} {y+3:.1f} 0 {y+3:.1f} "
            f"Q {w*.9:.1f} {y+3:.1f} {w+10:.1f} {y-5:.1f} Q {w*.7:.1f} {y-6:.1f} {w*.3:.1f} {y-12:.1f} "
            f"L {-w*.3:.1f} {y-12:.1f} Q {-w*.7:.1f} {y-6:.1f} {-(w+10):.1f} {y-5:.1f} Z'/>")
        y -= 8
    parts.append(f"<rect x='-.8' y='{y-16:.1f}' width='1.6' height='18'/>"
                 f"<circle cx='0' cy='{y-12:.1f}' r='2.2'/>")
    return f"<g transform='translate({cx},{by}) scale({s})' fill='{fill}'>{''.join(parts)}</g>"


def _stupa(cx, by, s, fill):
    return (f"<g transform='translate({cx},{by}) scale({s})' fill='{fill}'>"
            "<rect x='-22' y='-4' width='44' height='4'/><path d='M -16 -4 A 16 14 0 0 1 16 -4 Z'/>"
            "<rect x='-6' y='-24' width='12' height='7'/><ellipse cx='0' cy='-28' rx='6' ry='1.6'/>"
            "<ellipse cx='0' cy='-32' rx='4.6' ry='1.4'/><ellipse cx='0' cy='-36' rx='3.2' ry='1.2'/>"
            "<rect x='-.7' y='-46' width='1.4' height='10'/></g>")


def _lotus(x, y, s):
    petals = "".join(
        f"<path transform='rotate({a})' d='M 0 0 Q -7 -9 0 -21 Q 7 -9 0 0 Z' fill='url(#lot)'/>"
        for a in (-62, -38, -16, 16, 38, 62, 0))
    return (f"<g transform='translate({x},{y}) scale({s})'>"
            "<ellipse cx='0' cy='1' rx='26' ry='5' fill='#16344a' opacity='.85'/>" + petals +
            "<circle cx='0' cy='-4' r='2.4' fill='#ffd27a'/></g>")


def _diya(x, y, s):
    return (f"<g transform='translate({x},{y}) scale({s})'>"
            "<circle cx='0' cy='-6' r='22' fill='url(#dglow)'/>"
            "<path d='M -8 -2 Q 0 8 8 -2 Z' fill='#b5603a'/><ellipse cx='0' cy='-2' rx='8' ry='1.8' fill='#d98a54'/>"
            "<path class='fl' d='M 0 -3 Q -3.4 -8 0 -15 Q 3.4 -8 0 -3 Z' fill='#ffd88a'/></g>")


def background():
    rnd = random.Random(108)
    defs = [
        "<linearGradient id='sky' x1='0' y1='0' x2='0' y2='1'>"
        "<stop offset='0' stop-color='#080720'/><stop offset='.34' stop-color='#1f1649'/>"
        "<stop offset='.6' stop-color='#5b2a63'/><stop offset='.8' stop-color='#c4566a'/>"
        "<stop offset='.93' stop-color='#f19a62'/><stop offset='1' stop-color='#f9c97a'/></linearGradient>",
        "<radialGradient id='sun' cx='.5' cy='.5' r='.5'><stop offset='0' stop-color='#fff3d6'/>"
        "<stop offset='.6' stop-color='#ffc77e'/><stop offset='1' stop-color='#f58c5c'/></radialGradient>",
        "<linearGradient id='water' x1='0' y1='0' x2='0' y2='1'><stop offset='0' stop-color='#3a2455'/>"
        "<stop offset='.25' stop-color='#1d1640'/><stop offset='1' stop-color='#090818'/></linearGradient>",
        "<radialGradient id='vig' cx='.5' cy='.5' r='.75'><stop offset='.6' stop-color='#05040f' stop-opacity='0'/>"
        "<stop offset='1' stop-color='#05040f' stop-opacity='.55'/></radialGradient>",
        "<linearGradient id='lot' x1='0' y1='1' x2='0' y2='0'><stop offset='0' stop-color='#c9567c'/>"
        "<stop offset='1' stop-color='#ffc2d2'/></linearGradient>",
        _puff("dglow", "#ffb860", .55), _puff("sglow", "#ffcf94", .75),
        _puff("mist", "#f6bda0", .5), _puff("mist2", "#c9a0c8", .4),
    ]
    b = [f"<rect width='{W}' height='{H}' fill='url(#sky)'/>"]

    for _ in range(80):                                   # stars
        x, y = rnd.uniform(15, 1185), rnd.uniform(12, 300) ** 1.0
        if rnd.random() < .5:
            y = rnd.uniform(12, 170)
        b.append(f"<circle class='tw' cx='{x:.0f}' cy='{y:.0f}' r='{rnd.uniform(.5, 1.4):.1f}' fill='#fff7e6' "
                 f"style='animation-delay:{rnd.uniform(0, 4):.1f}s;animation-duration:{rnd.uniform(3, 6):.1f}s'/>")

    sx, sy = 605, 290                                      # sun + mandala
    b.append(f"<ellipse cx='{sx}' cy='{sy+20}' rx='430' ry='260' fill='url(#sglow)'/>")
    b.append(f"<circle cx='{sx}' cy='{sy}' r='168' fill='none' stroke='{GOLD}' stroke-width='.6' opacity='.3'/>")
    b.append(f"<circle cx='{sx}' cy='{sy}' r='122' fill='none' stroke='{GOLD}' stroke-width='1.2' "
             f"stroke-dasharray='.1 7' stroke-linecap='round' opacity='.7'/>")
    b.append(f"<circle cx='{sx}' cy='{sy}' r='108' fill='none' stroke='{GOLD}' stroke-width='.8' opacity='.5'/>")
    petals = "".join(
        f"<path transform='rotate({i*15} {sx} {sy})' d='M {sx} {sy-110} Q {sx+13} {sy-134} {sx} {sy-158} "
        f"Q {sx-13} {sy-134} {sx} {sy-110} Z' fill='none' stroke='{GOLD}' stroke-width='.7' opacity='.42'/>"
        for i in range(24))
    ticks = "".join(
        f"<line x1='{sx+171*math.sin(math.radians(i*5)):.1f}' y1='{sy-171*math.cos(math.radians(i*5)):.1f}' "
        f"x2='{sx+(177 if i%3==0 else 174)*math.sin(math.radians(i*5)):.1f}' "
        f"y2='{sy-(177 if i%3==0 else 174)*math.cos(math.radians(i*5)):.1f}' stroke='{GOLD}' stroke-width='.6' opacity='.4'/>"
        for i in range(72))
    b.append(f"<g class='rot'>{petals}{ticks}</g>")
    b.append(f"<circle cx='{sx}' cy='{sy}' r='92' fill='url(#sun)'/>")

    b.append(f"<g class='dr'><ellipse cx='320' cy='345' rx='300' ry='20' fill='url(#mist2)'/>"
             f"<ellipse cx='900' cy='352' rx='320' ry='20' fill='url(#mist2)'/></g>")
    layers = [(1, 362, 62, "#7d5688", .62), (2, 386, 58, "#573a72", .85),
              (3, 410, 46, "#382859", .95), (4, 432, 30, "#241a44", 1)]
    for i, (seed, base, amp, col, op) in enumerate(layers):
        b.append(f"<path d='{_ridge(seed*7, base, amp)}' fill='{col}' opacity='{op}'/>")
        b.append(f"<g class='dr' style='animation-duration:{40+i*9}s'>"
                 f"<ellipse cx='{300+i*220}' cy='{base+14}' rx='340' ry='15' fill='url(#mist)'/></g>")

    # mounds + monuments
    b.append("<path d='M 478 448 Q 540 400 605 396 Q 670 400 732 448 Z' fill='#17112f'/>")
    b.append("<path d='M 418 448 Q 450 414 472 410 Q 498 414 528 448 Z' fill='#2a1f4d'/>")
    b.append("<path d='M 716 448 Q 738 420 752 418 Q 770 420 790 448 Z' fill='#2a1f4d'/>")
    b.append(_pagoda(472, 411, .82, "#2a1f4d"))
    b.append(_stupa(752, 419, .78, "#2a1f4d"))
    b.append(_temple(605, 398, 1.1, "#100b26", "#ffcf8a"))

    b.append(f"<rect y='440' width='{W}' height='200' fill='url(#water)'/>")      # water
    b.append(f"<rect y='439' width='{W}' height='1.4' fill='{GOLD}' opacity='.45'/>")
    for i in range(15):                                                           # sun path
        w = 96 - i * 5.2 + rnd.uniform(-6, 6)
        b.append(f"<rect x='{605-w/2:.0f}' y='{450+i*11.5:.0f}' width='{max(w,8):.0f}' height='2.2' rx='1.1' "
                 f"fill='#ffcf8a' opacity='{.7-i*.042:.2f}'/>")
    for _ in range(26):
        x, y, w = rnd.uniform(0, 1200), rnd.uniform(455, 630), rnd.uniform(30, 110)
        b.append(f"<rect x='{x:.0f}' y='{y:.0f}' width='{w:.0f}' height='1' fill='#b79ad6' opacity='.16'/>")

    for x, y, s in [(488, 506, 1), (540, 566, 1.25), (592, 500, .85), (650, 548, 1.1),
                    (704, 512, .95), (756, 584, 1.3), (610, 606, .9), (452, 598, .8)]:
        b.append(_diya(x, y, s))
    b.append(_lotus(520, 604, 1.0))
    b.append(_lotus(720, 592, .85))
    b.append(_lotus(440, 520, .6))

    birds = "".join(
        f"<path d='M {x} {y} q 6 -7 12 0 q 6 -7 12 0'/>"
        for x, y in [(470, 150), (498, 134), (526, 158), (556, 142), (512, 176)])
    b.append(f"<g class='dr' stroke='#f9dcb4' stroke-width='1.6' fill='none' stroke-linecap='round' opacity='.7'>{birds}</g>")

    b.append(f"<rect width='{W}' height='{H}' fill='url(#vig)'/>")
    b.append(f"<rect x='12' y='12' width='{W-24}' height='{H-24}' rx='12' fill='none' stroke='{GOLD}' "
             f"stroke-width='.8' opacity='.4'/>")
    return "".join(defs), "".join(b)


# ----------------------------------------------------------------------------
# Panels
# ----------------------------------------------------------------------------
S = {"head": "#fff6e8", "text": "#f0e7f5", "sub": "#cbbcdb", "gold": GOLD}


def T(x, y, s, size=12, fill=None, weight=400, family=SANS, anchor="start", extra=""):
    return (f"<text x='{x}' y='{y}' font-family='{family}' font-size='{size}' font-weight='{weight}' "
            f"fill='{fill or S['text']}' text-anchor='{anchor}' {extra}>{s}</text>")


def heading(x, y, title, w):
    return (T(x, y, escape(title), 13, S["gold"], 600, SANS, extra="letter-spacing='.6'")
            + f"<rect x='{x}' y='{y+9}' width='{w}' height='1' fill='{S['gold']}' opacity='.35'/>")


def stat_card(x, y, value, label):
    fs = 22 if len(value) <= 7 else 18
    return (f"<rect x='{x}' y='{y}' width='152' height='60' rx='12' fill='#ffffff' fill-opacity='.07' "
            f"stroke='{S['gold']}' stroke-opacity='.35' stroke-width='.8'/>"
            + T(x + 76, y + 28, value, fs, S["head"], 500, MONO, "middle")
            + T(x + 76, y + 46, escape(label), 10, S["sub"], 400, SANS, "middle"))


def lang_chart(languages, x0, y0, w):
    out = [f"<clipPath id='lbar'><rect x='{x0}' y='{y0}' width='{w}' height='10' rx='5'/></clipPath>"]
    x = x0
    segs = []
    for lang, _, pct in languages:
        sw = w * pct / 100
        segs.append(f"<rect x='{x:.1f}' y='{y0}' width='{sw+.5:.1f}' height='10' "
                    f"fill='{LANG_COLORS.get(lang, '#9a8aa8')}'/>")
        x += sw
    out.append(f"<rect x='{x0}' y='{y0}' width='{w}' height='10' rx='5' fill='#ffffff' opacity='.1'/>")
    out.append(f"<g clip-path='url(#lbar)'>{''.join(segs)}</g>")
    for i, (lang, n, pct) in enumerate(languages):
        cy = y0 + 32 + i * 24
        out.append(f"<circle cx='{x0+6}' cy='{cy-4}' r='4.5' fill='{LANG_COLORS.get(lang, '#9a8aa8')}'/>")
        out.append(T(x0 + 20, cy, escape(lang), 12, S["text"]))
        out.append(T(x0 + w - 62, cy, fmt(n), 11, S["sub"], 400, MONO, "end"))
        out.append(T(x0 + w, cy, f"{pct:.1f}%", 11, S["head"], 500, MONO, "end"))
    return "".join(out)


def year_chart(per_year, x0, base_y, w, h):
    years = sorted(per_year)[-MAX_YEARS_SHOWN:]
    if not years:
        return T(x0, base_y - 20, "per-year data needs a token", 11, S["sub"])
    peak = max(per_year[y] for y in years) or 1
    gap = 8
    bw = min(30.0, (w - gap * (len(years) - 1)) / len(years))
    total_w = bw * len(years) + gap * (len(years) - 1)
    x = x0 + (w - total_w) / 2
    out = []
    for y in years:
        v = per_year[y]
        bh = max(2.0, v / peak * h)
        out.append(f"<rect x='{x:.1f}' y='{base_y-bh:.1f}' width='{bw:.1f}' height='{bh:.1f}' rx='4' "
                   f"fill='url(#bar)'/>")
        out.append(T(f"{x+bw/2:.1f}", f"{base_y-bh-5:.1f}", fmt(v), 9, S["head"], 400, MONO, "middle"))
        out.append(T(f"{x+bw/2:.1f}", base_y + 14, str(y), 9.5, S["sub"], 400, MONO, "middle"))
        x += bw + gap
    return ("<linearGradient id='bar' x1='0' y1='1' x2='0' y2='0'><stop offset='0' stop-color='#c9567c'/>"
            f"<stop offset='1' stop-color='{GOLD}'/></linearGradient>" + "".join(out))


def render_panels(stats):
    scrim = ("<rect x='40' y='40' width='380' height='560' rx='20' fill='#0b0920' fill-opacity='.58' "
             f"stroke='{GOLD}' stroke-opacity='.25'/>"
             "<rect x='800' y='40' width='360' height='560' rx='20' fill='#0b0920' fill-opacity='.58' "
             f"stroke='{GOLD}' stroke-opacity='.25'/>")

    contacts = [("Google Developer", USERNAME), ("X (Twitter)", f"@{USERNAME}"),
                ("Email", f"{USERNAME}@yahoo.com"), ("Google Play", USERNAME)]
    left = [T(60, 100, escape(stats["name"]), 50, S["head"], 600, DISP, extra="letter-spacing='.5'"),
            T(60, 130, "कृत्य । सहिष्णुता । मोक्षः", 14, S["sub"])]
    if stats["since"]:
        yrs = stats["years_active"]
        left.append(T(60, 152, f"on GitHub since {stats['since']} · {yrs} yr{'s' if yrs != 1 else ''}",
                      10.5, S["gold"], 400, MONO))
    left.append(heading(60, 190, "Connect", 340))
    for i, (label, value) in enumerate(contacts):
        yy = 220 + i * 26
        left.append(T(60, yy, escape(label), 11.5, S["text"], 600))
        left.append(T(188, yy, escape(value), 11.5, S["sub"]))
    for y, title, body in [
        (342, "Hobbies & Passions", "Reading · Exploring Places · Photography · Developer"),
        (410, "Programming Languages", "HTML · CSS · JavaScript · TypeScript · Python · C · C++"),
        (478, "Tools & Frameworks", "React · Docker · Express · FastAPI · REST · GitHub · RAG"),
    ]:
        left.append(heading(60, y, title, 340))
        left.append(T(60, y + 28, escape(body), 11.5, S["sub"]))
    left.append(T(60, 585, f"updated {format_ist_now()}", 9, S["sub"], 400, MONO, extra="opacity='.8'"))

    since = f"since {stats['since']}" if stats["since"] else "all-time"
    right = [
        stat_card(820, 62, fmt(stats["commits"]), f"commits · {since}"),
        stat_card(988, 62, fmt(stats["loc"]), "lines of code"),
        stat_card(820, 130, fmt(stats["repos"]), "repositories"),
        stat_card(988, 130, fmt(stats["stars"]), "stars earned"),
        heading(820, 232, "Languages · by lines of code", 320),
        lang_chart(stats["languages"], 820, 252, 320),
        heading(820, 450, "Commits per year", 320),
        year_chart(stats["per_year"], 820, 566, 320, 70),
    ]
    return scrim + "".join(left) + "".join(right)


def generate_svg(stats, theme="mandala"):
    defs, body = background()
    return ("<?xml version='1.0' encoding='UTF-8'?>\n"
            f"<svg viewBox='0 0 {W} {H}' xmlns='http://www.w3.org/2000/svg'>\n"
            f"<defs><style>{CSS}</style>{defs}</defs>\n{body}\n{render_panels(stats)}\n</svg>")


def main():
    print(f"Fetching stats for {USERNAME}...")
    stats = fetch_stats()
    print(json.dumps({k: v for k, v in stats.items() if k not in ("languages",)}, indent=2, default=str))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for theme in THEMES:
        svg = generate_svg(stats, theme)
        for name in [theme] + ALSO_WRITE_AS:
            path = OUT_DIR / f"github-banner-{name}.svg"
            path.write_text(svg, encoding="utf-8")
            print(f"Banner written to {path}")


if __name__ == "__main__":
    main()
